# Generated by Django 4.2.20 on 2025-04-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardPost',
        ),
    ]
